version: "2"
services:
  app:
    container_name: Addams_App_Prod
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production

  db:
    container_name: Addams_DB_Prod
    image: mysql:5.7
    ports:
      - "32000:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: addams
      MYSQL_USER: addams
      MYSQL_PASSWORD: family
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
