version: "2"
services:
  app_dev:
    container_name: Addams_App_Dev
    build: .
    links:
      - db_dev
    ports:
      - "5001:5000"
      - "5002:80"
    environment:
      FLASK_ENV: development
      MYSQL_ROOT_PASSWORD: $dev-mysql-root
      MYSQL_DATABASE: addams
      MYSQL_USER: $dev-mysql-user
      MYSQL_PASSWORD: $dev-mysql-password
      
  db_dev:
    container_name: Addams_DB_Dev
    image: mysql:5.7
    ports:
      - "32001:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $dev-mysql-root
      MYSQL_DATABASE: addams
      MYSQL_USER: $dev-mysql-user
      MYSQL_PASSWORD: $dev-mysql-password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
