variables:
  - group: dev-variable-group
  - group: prod-variable-group

trigger:
  batch: true
  branches:
    include:
      - develop

pool:
  name: 'Default'

stages:
  - stage: Dev_Deploy
    jobs:
    - job: Dev_Deploy
      steps:
        - checkout: self

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              set -e
              echo "Dev Deploy"
              whoami
              pwd
              ls -la
              #ufw status
            workingDirectory: "$(System.DefaultWorkingDirectory)"
          displayName: "Copy Dev Website files"
          env:
             ARM_SSH_KEY: $(de-vm-ssh-key)
             ARM_vmuser: $(dev-user)
             ARM_vmpasswd: $(dev-vm-passwd)
             ARM_vmip: $(dev-vm-ip)
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'SonarCloud'
            organization: 'addamsfamily'
            scannerMode: 'CLI'
            configMode: 'manual'
            cliProjectKey: 'AddamsFamily_AddamsFamily2022'
            cliProjectName: 'AddamsFamily2022'
            cliSources: '.'


  - stage: Dev_Unit_Tests
    jobs:
    - job: Dev_Test
      steps:
        - checkout: self

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              set -e
              echo "Dev Test"
              netstat -pnltu
              #curl -v http:// 13.74.152.222:5000
            workingDirectory: "$(System.DefaultWorkingDirectory)"
          displayName: "Perform Dev Unit Tests"

  - stage: Prod_Deploy
    dependsOn: [Dev_Unit_Tests]
    condition: succeeded('Dev_Unit_Tests')
    jobs:
    - deployment: Prod_Deploy
      continueOnError: false
      environment: Dev
      timeoutInMinutes: 5
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none

              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: |
                    set -e
                    echo "Prod Deploy"
                  workingDirectory: "$(System.DefaultWorkingDirectory)"
                displayName: "Copy Prod Website files"

  - stage: Prod_Unit_Test
    jobs:
    - job: Prod_Test
      steps:
        - checkout: self

        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              set -e
              echo "Prod Test"
            workingDirectory: "$(System.DefaultWorkingDirectory)"
          displayName: "Perform Prod Unit tests"  

