name: Deploy to Amazon ECS

on:
  push:
    branches:
      - ciaran_version/remove_prod
      
jobs:
  deploy:
    name: Deploy to Prod EC2
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Deploy app to EC2 server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      
      - name: Launch web app 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            set -e
            sudo docker-compose -f addams/docker-compose_dev.yml down
            sudo docker-compose -f addams/docker-compose_dev.yml up --build -d

      - name: Sleep for 5s
        run: sleep 5s
        shell: bash

      - name: install K6 CLI
        run:  |
          sudo apt-get update
          sudo snap install k6

      - name: K6 book
        run: |
          cd performance
          k6 run --summary-export book_output.json k6_book.js

      - name: K6 login
        run: |
          cd performance
          k6 run --summary-export login_output.json k6_login.js

      - name: Store Book benchmark 
        uses: cohogainLYIT/github-action-benchmark@v1
        with:
          name: K6 Book benchmark
          tool: 'k6_book'
          output-file-path: performance/book_output.json
          github-token: ${{ secrets.TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@ktrz'

      - name: Store Login benchmark 
        uses: cohogainLYIT/github-action-benchmark@v1
        with:
          name: K6 Login benchmark
          tool: 'k6_login'
          output-file-path: performance/login_output.json
          github-token: ${{ secrets.TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@ktrz'
