name: Python Example with pytest
on:
  push:
    branches:
      - ciaran_version/remove_prod

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run pytest-benchmark benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run benchmark
        run: |
          cd Unit_test
          pip install -r requirements.txt
          pytest bench.py --benchmark-json output.json
